### ISSUE TITLE
DBAL.php is missing "url" as constant

### ISSUE THREAD

**Issue by gertvdb** [symplify/amnesia#1]
DBAL.php is missing "url" as constant 

<img width="389" alt="Screenshot 2021-05-20 at 16 23 56" src="https://user-images.githubusercontent.com/7106435/118995889-c8789000-b987-11eb-8907-4e4d28ec6afc.png">

**Comment by TomasVotruba** [comment]
Hi, thanks for report.
Please send PR to add it there:
https://github.com/symplify/symplify

**Comment by gertvdb** [comment]
Will do, sorry forgot issue should be reported in monorepo.

**Comment by TomasVotruba** [comment]
My bad, I forgot to disable issues here
